-- =====================================================================
-- FILTER: APPENDIX NUMBERING NORMALIZATION FOR PANDOC HTML OUTPUT
-- =====================================================================
-- This Lua filter rewrites appendix heading numbering and internal
-- cross-reference text for HTML generated by Pandoc from LaTeX input.
-- It is specifically intended to correct the mismatch between LaTeX
-- appendix semantics (e.g., Appendix A / A.1 / A.1.2) and Pandoc's
-- default HTML rendering, which may otherwise flatten appendices into
-- ordinary numeric sections (e.g., 13 / 13.1 / 13.1.2).
-- =====================================================================

-- ---------------------------------------------------------------------
-- GLOBAL APPENDIX REFERENCE MAP
-- ---------------------------------------------------------------------
-- Stores the normalized appendix numbering associated with each header
-- ID after header traversal. This map is later used during link
-- rewriting so that internal references targeting appendix anchors can
-- be replaced with the correct appendix-style numbering.
-- ---------------------------------------------------------------------
local appendix_map = {}

-- ---------------------------------------------------------------------
-- HELPER: STRINGIFY PANDOC INLINE CONTENT
-- ---------------------------------------------------------------------
-- Converts a Pandoc inline or block content structure into plain text
-- using pandoc.utils.stringify(). This is used whenever header content
-- or link text must be evaluated as normal text for matching or
-- reconstruction.
-- ---------------------------------------------------------------------
local function stringify(x)
  return pandoc.utils.stringify(x)
end

-- ---------------------------------------------------------------------
-- HELPER: TRIM LEADING / TRAILING WHITESPACE
-- ---------------------------------------------------------------------
-- Normalizes text by removing leading and trailing whitespace. This is
-- used before and after pattern-based prefix stripping so that
-- reconstructed header titles remain clean and deterministic.
-- ---------------------------------------------------------------------
local function trim(s)
  return (s:gsub("^%s+", ""):gsub("%s+$", ""))
end

-- ---------------------------------------------------------------------
-- HELPER: DETECT APPENDIX LABEL IDS
-- ---------------------------------------------------------------------
-- Returns true when a header ID begins with "sec:appendix". This is the
-- primary label-based signal used to detect the single appendix in the
-- AWS lab document.
-- ---------------------------------------------------------------------
local function is_appendix_id(id)
  if not id then
    return false
  end
  return id:match("^sec:appendix") ~= nil
end

-- ---------------------------------------------------------------------
-- HELPER: DETECT APPENDIX TITLES
-- ---------------------------------------------------------------------
-- Returns true when the visible header text begins with "Appendix".
-- This provides a title-based fallback for detecting the appendix when
-- a label alone is not sufficient.
-- ---------------------------------------------------------------------
local function is_appendix_title(text)
  text = trim(text)
  return text:match("^[Aa]ppendix\b") ~= nil
end

-- ---------------------------------------------------------------------
-- HELPER: STRIP TOP-LEVEL APPENDIX PREFIX FROM TITLES
-- ---------------------------------------------------------------------
-- Removes manual appendix prefixes that may already be embedded in the
-- top-level appendix heading before the filter inserts normalized
-- numbering. This supports forms such as:
--   - "Appendix: Design Constraints and Limitations"
--   - "Appendix A. Design Constraints and Limitations"
--   - "Appendix Design Constraints and Limitations"
-- ---------------------------------------------------------------------
local function strip_top_level_appendix_prefix(text)
  text = trim(text)
  text = text:gsub("^%s*[Aa]ppendix%s*:%s*", "", 1)
  text = text:gsub("^%s*[Aa]ppendix%s+[A-Za-z]%.?%s*", "", 1)
  text = text:gsub("^%s*[Aa]ppendix%.?%s*", "", 1)
  return trim(text)
end

-- ---------------------------------------------------------------------
-- HELPER: STRIP MANUAL LOWER-LEVEL APPENDIX PREFIXES
-- ---------------------------------------------------------------------
-- Removes manual appendix numbering that may already be embedded in
-- lower-level appendix headings before the filter inserts normalized
-- numbering. This supports forms such as:
--   - "A.1 Title"
--   - "A.1.2 Title"
--   - "A.1.2.3 Title"
-- ---------------------------------------------------------------------
local function strip_manual_prefix(text)
  text = trim(text)
  text = text:gsub("^A%.%d+%.%d+%.%d+%.?%s+", "", 1)
  text = text:gsub("^A%.%d+%.%d+%.?%s+", "", 1)
  text = text:gsub("^A%.%d+%.?%s+", "", 1)
  return trim(text)
end

-- ---------------------------------------------------------------------
-- HELPER: BUILD NORMALIZED HEADER CONTENT
-- ---------------------------------------------------------------------
-- Constructs replacement inline content for appendix headers. For the
-- top-level appendix section, the visible prefix is rendered as
-- "Appendix A." within a header-section-number span so that the heading
-- and TOC remain aligned with Pandoc's numbered-header structure. For
-- lower-level appendix headings, only the compact form (e.g., "A.1.2")
-- is emitted before the title text.
-- ---------------------------------------------------------------------
local function make_header_content(number, title_text, is_appendix_top)
  if is_appendix_top then
    return {
      pandoc.Span(
        { pandoc.Str("Appendix"), pandoc.Space(), pandoc.Str(number .. ".") },
        pandoc.Attr("", { "header-section-number" })
      ),
      pandoc.Space(),
      pandoc.Str(title_text)
    }
  else
    return {
      pandoc.Span(
        { pandoc.Str(number) },
        pandoc.Attr("", { "header-section-number" })
      ),
      pandoc.Space(),
      pandoc.Str(title_text)
    }
  end
end

-- ---------------------------------------------------------------------
-- PASS 1: COLLECT APPENDIX IDS AND REWRITE HEADERS
-- ---------------------------------------------------------------------
-- Traverses document headers in order, detects the single appendix,
-- maintains appendix counters, records normalized values in
-- appendix_map, and rewrites visible header text accordingly.
--
-- Behavior:
--   - The top-level appendix header becomes "Appendix A."
--   - Level-2 appendix headers become "A.1", "A.2", etc.
--   - Level-3 appendix headers become "A.1.1", "A.2.1", etc.
--   - Level-4 appendix headers become "A.1.1.1", etc.
--
-- Once a top-level appendix has been detected, subsequent lower-level
-- headers are treated as belonging to Appendix A until another level-1
-- header ends appendix scope.
-- ---------------------------------------------------------------------
local function collect_and_rewrite_headers(doc)
  local in_appendix = false
  local counters = { subsection = 0, subsubsection = 0, level4 = 0 }

  for _, block in ipairs(doc.blocks) do
    if block.t == "Header" then
      local id = block.identifier or ""
      local raw = trim(stringify(block.content))

      -- ---------------------------------------------------------------
      -- LEVEL 1: TOP-LEVEL APPENDIX SECTION
      -- ---------------------------------------------------------------
      -- Detects the single appendix by label or by visible title text,
      -- resets appendix counters, stores the normalized top-level value
      -- "A" in the map, strips any manual appendix prefix from the
      -- heading text, and rewrites the visible header as
      -- "Appendix A. <Title>".
      -- ---------------------------------------------------------------
      if block.level == 1 then
        if is_appendix_id(id) or is_appendix_title(raw) then
          in_appendix = true
          counters = { subsection = 0, subsubsection = 0, level4 = 0 }

          if id ~= "" then
            appendix_map[id] = "A"
          end

          local title = strip_top_level_appendix_prefix(raw)
          block.content = make_header_content("A", title, true)
        else
          in_appendix = false
        end

      -- ---------------------------------------------------------------
      -- LEVEL 2: APPENDIX SUBSECTION
      -- ---------------------------------------------------------------
      -- Increments the Appendix A subsection counter, resets deeper
      -- counters, stores the normalized value (e.g., "A.1") in the map,
      -- strips any manual appendix numbering from the source title, and
      -- rewrites the visible heading content.
      -- ---------------------------------------------------------------
      elseif in_appendix and block.level == 2 then
        counters.subsection = counters.subsection + 1
        counters.subsubsection = 0
        counters.level4 = 0

        local num = string.format("A.%d", counters.subsection)
        if id ~= "" then
          appendix_map[id] = num
        end

        local title = strip_manual_prefix(raw)
        block.content = make_header_content(num, title, false)

      -- ---------------------------------------------------------------
      -- LEVEL 3: APPENDIX SUBSUBSECTION
      -- ---------------------------------------------------------------
      -- Increments the Appendix A subsubsection counter, resets the
      -- level-4 counter, stores the normalized value (e.g., "A.1.2")
      -- in the map, strips any manual appendix numbering from the
      -- source title, and rewrites the visible heading content.
      -- ---------------------------------------------------------------
      elseif in_appendix and block.level == 3 then
        counters.subsubsection = counters.subsubsection + 1
        counters.level4 = 0

        local num = string.format("A.%d.%d", counters.subsection, counters.subsubsection)
        if id ~= "" then
          appendix_map[id] = num
        end

        local title = strip_manual_prefix(raw)
        block.content = make_header_content(num, title, false)

      -- ---------------------------------------------------------------
      -- LEVEL 4: OPTIONAL DEEPER APPENDIX HEADING SUPPORT
      -- ---------------------------------------------------------------
      -- Supports one additional heading depth for completeness. It
      -- increments the level-4 counter, stores the normalized value
      -- (e.g., "A.1.2.1") in the map, strips manual appendix numbering
      -- from the source title, and rewrites the visible heading
      -- content.
      -- ---------------------------------------------------------------
      elseif in_appendix and block.level == 4 then
        counters.level4 = counters.level4 + 1

        local num = string.format("A.%d.%d.%d", counters.subsection, counters.subsubsection, counters.level4)
        if id ~= "" then
          appendix_map[id] = num
        end

        local title = strip_manual_prefix(raw)
        block.content = make_header_content(num, title, false)
      end
    end
  end

  return doc
end

-- ---------------------------------------------------------------------
-- PASS 2: REWRITE INTERNAL LINK TEXT FOR APPENDIX REFERENCES
-- ---------------------------------------------------------------------
-- Rewrites link text for internal links that target appendix IDs found
-- in appendix_map. This preserves the original anchor target while
-- changing only the visible link text.
--
-- Supported visible input forms include:
--   - "10"
--   - "10.1"
--   - "10.1.2"
--   - "Section 10.1.2"
--   - "Appendix 10"
--
-- These are rewritten to normalized appendix forms such as:
--   - "A"
--   - "A.1"
--   - "A.1.2"
--   - "Section A.1.2"
--   - "Appendix A"
-- ---------------------------------------------------------------------
local function rewrite_link_text(link)
  local target = link.target or ""
  local id = target:match("^#(.+)$")
  if not id then
    return link
  end

  local appendix_num = appendix_map[id]
  if not appendix_num then
    return link
  end

  local text = stringify(link.content)

  -- ---------------------------------------------------------------
  -- CASE 1: BARE NUMERIC REFERENCE
  -- ---------------------------------------------------------------
  -- Rewrites plain numeric link text such as "10", "10.1", or "10.1.2"
  -- to the normalized appendix form (e.g., "A", "A.1", "A.1.2").
  -- ---------------------------------------------------------------
  if text:match("^%d+$")
    or text:match("^%d+%.%d+$")
    or text:match("^%d+%.%d+%.%d+$")
    or text:match("^%d+%.%d+%.%d+%.%d+$")
  then
    link.content = { pandoc.Str(appendix_num) }
    return link
  end

  -- ---------------------------------------------------------------
  -- CASE 2: "SECTION N..." STYLE REFERENCE
  -- ---------------------------------------------------------------
  -- Rewrites visible link text of the form "Section 10.2.1" to
  -- "Section A.2.1" while preserving the internal anchor target.
  -- ---------------------------------------------------------------
  if text:match("^Section%s+%d+[%d%.]*$") then
    link.content = {
      pandoc.Str("Section"),
      pandoc.Space(),
      pandoc.Str(appendix_num)
    }
    return link
  end

  -- ---------------------------------------------------------------
  -- CASE 3: "APPENDIX N..." STYLE REFERENCE
  -- ---------------------------------------------------------------
  -- Rewrites visible link text of the form "Appendix 10" to
  -- "Appendix A" for the single appendix in the AWS lab.
  -- ---------------------------------------------------------------
  if text:match("^Appendix%s+%d+[%d%.]*$") then
    link.content = { pandoc.Str("Appendix A") }
    return link
  end

  return link
end

-- ---------------------------------------------------------------------
-- FILTER ENTRY POINT: DOCUMENT-LEVEL TWO-PASS TRANSFORMATION
-- ---------------------------------------------------------------------
-- Executes the filter as a document-level transformation. The first
-- pass rewrites appendix headers and records normalized numbering in the
-- appendix_map. The second pass walks the document and rewrites any
-- qualifying internal links that target those appendix IDs. This order
-- is required so that appendix numbering is known before link text
-- replacement occurs.
-- ---------------------------------------------------------------------
function Pandoc(doc)
  doc = collect_and_rewrite_headers(doc)
  doc = doc:walk({
    Link = rewrite_link_text
  })
  return doc
end
